coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
    patch:
      default:
        informational: true
        target: 95%
        threshold: 10%

comment:
    layout: "condensed_header, condensed_files, condensed_footer"
    hide_project_coverage: TRUE # set to true
