[GLOBAL]
pants_version = "2.18.0rc1"
backend_packages = [
	"pants.backend.python",
	"pants.backend.experimental.python",
	"pants.backend.python.lint.black",
	"pants.backend.python.lint.isort",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy"
]
pants_ignore = ["!cicd/secrets.yml"]

[source]

[python]
interpreter_constraints = ["CPython>=3.8"]
enable_resolves = true

[python.resolves]
python-default = "cicd/python-default.lock"
mypy = "cicd/mypy.lock"
black = "cicd/black.lock"

[pylint]
config = ".pylintrc"

[flake8]
config = ".flake8"

[black]
args = ["--use-tabs"]
console_script = "tan"
install_from_resolve = "black"
interpreter_constraints = ["CPython>=3.8"]

[test]
use_coverage = true
extra_env_vars = ["integration_test_secrets", "INTEGRATION_PRINT_OUTPUT"]

[coverage-py]
report = ["xml", "html"]

[mypy]
install_from_resolve = "mypy"
interpreter_constraints = ["CPython>=3.8"]
extra_type_stubs = ["types-PyYAML", "types-requests"]
extra_type_stubs_lockfile = "cicd/mypy_stubs.lock"

[anonymous-telemetry]
enabled = true
repo_id = "5c263cce-11ff-3ab5-a552-01e94b0c9d60"
