[GLOBAL]
pants_version = "2.13.0"
backend_packages = [
	"pants.backend.python",
	"pants.backend.python.lint.black",
	"pants.backend.python.lint.isort",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy"
]

use_deprecated_directory_cli_args_semantics = false # remove 2.14
[source]

[pylint]
config = ".pylintrc"

[flake8]
config = ".flake8"

[black]
args = ["--use-tabs"]
console_script = "tan"
version = "tan==21.14"
lockfile = "cicd/tan.lockfile"
extra_requirements = ["click!=8.1.*", "typing-extensions>=3.10.0.0"]

[test]
use_coverage = true

[coverage-py]
report = ["xml", "html"]

[mypy]
lockfile = "cicd/mypy.lock"

#extra_requirements.add = ["pytest"]
extra_type_stubs = ["types-PyYAML", "types-requests"]
