[GLOBAL]
pants_version = "2.13.0"
backend_packages = [
	"pants.backend.python",
	"pants.backend.python.lint.black",
	"pants.backend.python.lint.isort",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy"
]
pants_ignore = ["!cicd/secrets.yml"]

use_deprecated_directory_cli_args_semantics = false # remove 2.14
[source]

[python]
interpreter_constraints = ["CPython>=3.8"]

[pylint]
config = ".pylintrc"

[flake8]
config = ".flake8"

[black]
args = ["--use-tabs"]
console_script = "tan"
version = "tan==21.14"
lockfile = "cicd/tan.lockfile"
extra_requirements = ["click!=8.1.*", "typing-extensions>=3.10.0.0"]

[test]
use_coverage = true
extra_env_vars = ["integration_test_secrets"]

[coverage-py]
report = ["xml", "html"]

[mypy]
lockfile = "cicd/mypy.lock"

#extra_requirements.add = ["pytest"]
extra_type_stubs = ["types-PyYAML", "types-requests"]

[anonymous-telemetry]
enabled = true
repo_id = "5c263cce-11ff-3ab5-a552-01e94b0c9d60"
