[GLOBAL]
pants_version = "2.26.0.dev5"
backend_packages = [
	"pants.backend.python",
	"pants.backend.experimental.python",
	"pants.backend.experimental.python.lint.ruff.check",
	"pants.backend.experimental.python.lint.ruff.format",
	"pants.backend.python.lint.isort",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.autoflake",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy",
	"pants.backend.experimental.adhoc",
]
pants_ignore = ["!cicd/secrets.yml"]
[source]

[python]
interpreter_constraints = ["CPython>=3.10"]
enable_resolves = true

[python.resolves]
python-default = "cicd/python-default.lock"
mypy = "cicd/mypy.lock"
black = "cicd/black.lock"

[setup-py-generation]
first_party_dependency_version_scheme = "compatible"

[pylint]
config = ".pylintrc"

[flake8]
config = ".flake8"
install_from_resolve = "tools"
requirements = ["flake8"]

[test]
use_coverage = true
extra_env_vars = ["integration_test_secrets", "INTEGRATION_PRINT_OUTPUT", "AZURE_CONFIG_DIR"]

[coverage-py]
report = ["xml", "html"]

[mypy]
install_from_resolve = "mypy"
requirements = ["//:mypy"]
interpreter_constraints = ["CPython>=3.9"]

[ruff]
config = "pyproject.toml"

[update-build-files]
formatter = "ruff"
