[GLOBAL]
pants_version = "2.13.0"
backend_packages = [
	"pants.backend.python",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy"
]

use_deprecated_directory_cli_args_semantics = false # remove 2.14
[source]

[pylint]
config = ".pylintrc"

[flake8]
config = ".flake8"

[test]
use_coverage = true

[coverage-py]
report = ["xml", "html"]

[mypy]
lockfile = "cicd/mypy.lock"

#extra_requirements.add = ["pytest"]
extra_type_stubs = ["types-PyYAML", "types-requests"]
