[GLOBAL]
pants_version = "2.22.0rc0"
backend_packages = [
	"pants.backend.python",
	"pants.backend.experimental.python",
	"pants.backend.python.lint.black",
	"pants.backend.python.lint.isort",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.pylint",
	"pants.backend.python.typecheck.mypy",
	"pants.backend.experimental.adhoc",
]
pants_ignore = ["!cicd/secrets.yml"]
[source]

[python]
interpreter_constraints = ["CPython>=3.9"]
enable_resolves = true

[python.resolves]
python-default = "cicd/python-default.lock"
mypy = "cicd/mypy.lock"
black = "cicd/black.lock"

[pylint]
config = ".pylintrc"

[flake8]
config = ".flake8"

[black]
args = ["--use-tabs"]
console_script = "tan"
install_from_resolve = "black"
interpreter_constraints = ["CPython>=3.9"]

[test]
use_coverage = true
extra_env_vars = ["integration_test_secrets", "INTEGRATION_PRINT_OUTPUT", "AZURE_CONFIG_DIR"]

[coverage-py]
report = ["xml", "html"]

[mypy]
install_from_resolve = "mypy"
requirements = ["//:mypy"]
interpreter_constraints = ["CPython>=3.9"]

[anonymous-telemetry]
enabled = true
repo_id = "5c263cce-11ff-3ab5-a552-01e94b0c9d60"
